steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'frontend/Dockerfile',
    '--build-arg', 'NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=${_MAPBOX_TOKEN}',
    '-t', 'gcr.io/$PROJECT_ID/dontcollapse',
    './frontend'
  ]
images:
  - 'gcr.io/$PROJECT_ID/dontcollapse'

substitutions:
  _MAPBOX_TOKEN: ''