import json
from google.adk.agents import LlmAgent, LoopAgent
from google.adk.tools import FunctionTool

def simulate_shelter_status(zone_id: str) -> bool:
    """Mock test: returns True if a shelter in the zone is safe, False if it is flooded."""
    # A simple deterministic rule to fail some zones for the self-correction demonstration
    if zone_id in ["Z001", "Z003", "Z005"]: 
        return False
    return True

verify_tool = FunctionTool(func=simulate_shelter_status)

drafter_llm = LlmAgent(
    name="Drafter",
    model="gemini-2.5-flash",
    description="Drafts recommendations and compiles the final standard JSON. Self-corrects if verification fails.",
    instruction="""
    You are the Dispatcher. You must read the scores generated by the parallel evaluators and the user's picked scenario.
    You will draft evacuation and resilience actions.
    
    CRITICAL INSTRUCTION FOR SELF-CORRECTION (Loop requirement):
    Before completing, you MUST use the `simulate_shelter_status` tool to check if the primary zone you are recommending actions for is safe.
    If the tool returns False (Flooded), you MUST generate a new recommendation that avoids routing to that zone and explicitly state: "Self-Correction Activated: Primary shelter flooded, rerouting..."
    
    You must output a strictly formatted JSON array conforming to exactly this structure, matching what the frontend expects:
    {
      "summary": "2-3 sentences explaining overarching threat.",
      "score": 0-100,
      "affected": "Primary region affected",
      "actions": [ { "id": "uuid", "title": "short title", "detail": "explanation", "urgency": "critical"|"warning" } ],
      "logs": [ "log 1", "log 2" ],
      "rankedAreas": [ { "name": "Zone Name", "score": 85, "reason": "why" } ],
      "infrastructureScores": [
        { "id": "roads", "label": "Major Arteries", "score": 80 },
        { "id": "power", "label": "Power Grid", "score": 90 }
      ],
      "actionPayload": { "action": "deploy_pumps", "coordinates": [] }
    }
    
    If you successfully generated valid instructions, set the 'status' flag inside your internal reasoning to 'COMPLETE'.
    """,
    tools=[verify_tool],
    output_key="final_output"
)

# Use LoopAgent to allow for self-correction as required by ADK Rubric
# Not all ADK versions have the exact same LoopAgent spec. Assuming it loops the sub-agent until stopped.
dispatcher_agent = LoopAgent(
    name="DispatcherLoop",
    description="The Dispatcher. Uses a Loop workflow to double-check its work and self-correct.",
    sub_agents=[drafter_llm],
    max_iterations=2
)
